# -*- coding: utf-8 -*-
"""scrapping main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kkh47dvsR407rGhY1_S_bwA-q3ZZEEqA
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd

# Function to scrape prices
def scrape_prices(url):
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
    }
    prices = []

    while url:
        response = requests.get(url, headers=headers)
        soup = BeautifulSoup(response.text, 'html.parser')

        # Find all elements with the class 'amount'
        items = soup.find_all(class_='amount')

        for item in items:
            price = item.text.replace('AED', '').strip()  # Clean up the price text
            prices.append(float(price))

        # Find the link to the next page
        next_button = soup.find('a', attrs={'rel': 'next'})
        if next_button:
            url = next_button['href']
        else:
            break

    return prices

# Main execution
url = 'https://www.noon.com/uae-en/sports-and-outdoors/exercise-and-fitness/yoga-16328/?limit=150&sort%5Bby%5D=popularity&sort%5Bdir%5D=desc'
prices = scrape_prices(url)

# Save prices to CSV
csv_file = 'yoga_prices.csv'
pd.DataFrame(prices, columns=['Price']).to_csv(csv_file, index=False)

# Print scraped prices
print(f"Scraped Prices:\n{prices}")